---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 The Linux Foundation <matthew.watkins@linuxfoundation.org>

version: 2
updates:
  # prettier-ignore
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "[dependabot] Chore:"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
